#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action

main() {
    action=$1
    shift

    case $action in
        help|list|show|disable|enable)
            help_for_${action}
            ;;
        ?*)
            echo "${cw_BINNAME}: no such topic: ${action}"
            echo ""
            general_help
            ;;
        *)
            general_help
            ;;
    esac
}

help_for_disable() {
    cat <<EOF
  SYNOPSIS:

    $cw_BINNAME tips disable

  DESCRIPTION:

    Disable display of tips on login.

EOF
}

help_for_enable() {
    cat <<EOF
  SYNOPSIS:

    $cw_BINNAME tips enable

  DESCRIPTION:

    Enable display of tips on login.

EOF
}

help_for_list() {
    cat <<EOF
  SYNOPSIS:

    $cw_BINNAME tips [list]

  DESCRIPTION:

    Display a list of available tips.

EOF
}

help_for_show() {
    cat <<EOF
  SYNOPSIS:

    $cw_BINNAME tips [show] [--short] [--random|<topic>]

  DESCRIPTION:

    Show a tip regarding <topic> or, with --random, a random tip.

    For short (one line) tips, supply the --short flag.

EOF
}

help_for_help() {
    cat <<EOF
  SYNOPSIS:

    $cw_BINNAME tips help [<command>]

  DESCRIPTION:

    Get help with tips commands.  If no <command> is specified, show
    some general help.

EOF
}

general_help() {
    local binname
    binname="${cw_BINNAME% *}"
    cat <<EOF
  NAME:

    ${binname}

  DESCRIPTION:

    Helpful documents explaining how to get the most out of your
    research environment.

  COMMANDS:

EOF
printf "    %-24s  %s\n" "$binname help" "More help about this command."
printf "    %-24s  %s\n" "$binname list" "List available tips."
printf "    %-24s  %s\n" "$binname show" "Display a tip."
printf "    %-24s  %s\n" "$binname enable" "Enable display of tips on login."
printf "    %-24s  %s\n" "$binname disable" "Disable display of tips on login."
cat <<EOF

Please report bugs to support@alces-software.com
Alces Software home page: <http://alces-software.com>
EOF
}

main "$@"
