#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Flight Direct.
#
# Flight Direct is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Flight Direct is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Flight Direct, please visit:
# https://github.com/alces-software/flight-direct
#==============================================================================
main() {
    local path options fsid managed_uuid target found
    while read path options; do
	fsid=$(echo "$options" | sed 's/.*fsid=\([^,]*\).*/\1/g')
	if [ "$fsid" ]; then
	    managed_uuid="$(uuid -v5 0103f694-c5a8-5779-af10-3668872f329d $path)"
	    if [ "$fsid" == "$managed_uuid" ]; then
		target="$(echo "$options" | sed 's/\([^(]*\).*/\1/g')"
		echo "$target:$path"
		found=true
	    fi
	fi
    done <<< "$(exportfs -v)"
    if [ -z "$found" ]; then
	action_die "no NFS exports found"
    fi
}

require action

main "$@"
