#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler support script
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################

. $(dirname ${BASH_SOURCE[-1]})/common

hostname="$1"
group="$2"
tmpfile="$(mktemp /tmp/cluster-slurm.add-node-to-partition.XXXXXXXX)"


if _lock; then
  echo "Adding node $hostname to partition $group"
  sed -i -e "s/\(PartitionName=$group .*\)Nodes=\([^ ]*\)\(.*\)/\1 Nodes=$hostname,\2 \3/" \
         -e "s/,,/,/" \
         "${cw_CLUSTER_SLURM_config}"
  _unlock
else
  echo "Could not obtain lock; can't update partition"
fi

rm -f "$tmpfile"
