#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler support functions
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################

_lock() {
    mkdir -p "${cw_ROOT}"/var/lock
    exec 9> "${cw_ROOT}"/var/lock/cluster-slurm.lock && flock -w30 9
}

_unlock() {
    exec 9>&-
}
