#!/bin/bash
################################################################################
##
## Alces Flight Direct - Event hook
## Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    cw_ROOT=${cw_ROOT:-$FL_ROOT}
    source "${FL_ROOT}"/etc/runtime.sh
    kernel_load
}

main() {
    local slots

    eval "$(member_parse)"
    log "Member data parsed: ${cw_MEMBER_name} (${cw_MEMBER_ip}) -- ${cw_MEMBER_tags}"

    slots=$(member_find_tag "slots" "${cw_MEMBER_tags}")

    if [ "${cw_MEMBER_role}" == "compute" ]; then
        log "${cw_MEMBER_name} is Slurm compute node"
	${_SLURM} add-node "${cw_MEMBER_name}" "${slots:-1}" 2>&1 | log_blob
    else
        echo "${cw_MEMBER_name} is non-compute node" >> /tmp/flight-slurm.log
	${_SLURM} add-node "${cw_MEMBER_name}" "1" "" "FUTURE" 2>&1 | log_blob
    fi
}

setup
require member
require handler
require log

mkdir -p /var/log/flight
log_set_default /var/log/flight/flight-slurm.log

_SLURM="${cw_ROOT}/bin/flight slurm"

handler_tee main "$@"
