#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require document
require ruby

_replace_tags() {
  local input output
  input="$1"
  output="$2"
  if [ -f "${cw_ROOT}/etc/site/config.yml" ]; then
      ruby_run <<RUBY
require 'yaml'
replacements = YAML.load_file('${cw_ROOT}/etc/site/config.yml')
content = File.read("${input}")
replacements.each do |k,v|
  content.gsub!("%#{k.upcase}%", v.to_s)
end
File.write("${output}", content)
RUBY
  else
    cp "${input}" "${output}"
  fi
}

main() {
    local idx guide tmp
    idx="$1"
    if guide="$(document_get "$idx" about .md)"; then
        tmp="$(mktemp /tmp/about.XXXXXXXX)"
        _replace_tags "${guide}" "${tmp}"
        document_show "${tmp}" "Alces HPC Tool Suite"
        rm -f "${tmp}"
    else
        errlvl=$?
        if [ $errlvl == 1 ]; then
            action_die "no documents found"
        elif [ $errlvl == 3 ]; then
            action_die "please specify a name"
        else
            action_die "invalid document requested: ${idx}"
        fi
    fi
    action_cleanup
}

main "$@"
