#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Flight Direct.
#
# Flight Direct is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Flight Direct is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Flight Direct, please visit:
# https://github.com/alces-software/flight-direct
#==============================================================================
_stop_slurmd() {
    if ! systemctl -q is-active flight-slurm-slurmd; then
	echo "Flight Slurm compute node service is not running."
    elif systemctl -q stop flight-slurm-slurmd; then
	echo "Flight Slurm compute node service stopped."
    else
	echo "Failed to stop Flight Slurm compute node service."
    fi
}

_stop_slurmctld() {
    if ! systemctl -q is-active flight-slurm-slurmctld; then
	echo "Flight Slurm management service is not running."
    elif systemctl -q stop flight-slurm-slurmctld; then
	echo "Flight Slurm management service stopped."
    else
	echo "Failed to stop Flight Slurm management service."
    fi
}

_stop_slurm() {
    if [ "$FL_CONFIG_ROLE" == "login" ]; then
	_stop_slurmctld
    else
	_stop_slurmd
    fi
}

_stop_munged() {
    if ! systemctl -q is-active flight-slurm-munged; then
	echo "Flight Slurm authentication service is not running."
    elif systemctl -q stop flight-slurm-munged; then
	echo "Flight Slurm authentication service stopped."
    else
	echo "Failed to stop Flight Slurm authentication service."
    fi
}

main() {
    _stop_slurm
    _stop_munged
}

main "$@"
