#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Flight Direct.
#
# Flight Direct is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Flight Direct is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Flight Direct, please visit:
# https://github.com/alces-software/flight-direct
#==============================================================================
main() {
    local net path export
    path="$1"

    if [ -z "$path" ]; then
	action_die "Usage: ${cw_BINNAME} <path>"
    fi

    if network_is_ec2; then
	net=$(network_get_ec2_vpc_cidr_block)
    else
	net=$(network_get_iface_network $(network_get_first_iface))
    fi

    export="${net}:${path}"
    if exportfs -u "$export" 2>/dev/null; then
	echo "Export removed: $export"
    else
	action_die "could not unexport: ${path}"
    fi
}

require action
require network

main "$@"
