#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.rc ]; then
            source "${a}"/clusterware/config.rc
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
  local phase temp_dir
  phase="$1"

  files_load_config clusterware
  files_load_config --optional flight

  version="${cw_FLIGHT_release:-${cw_VERSION}}"

  # Fetch appropriate updates from S3
  if curl -L -o /tmp/updates.tar.gz \
          https://s3-eu-west-1.amazonaws.com/packages.alces-software.com/clusterware/dist/share/updates/${version}.tar.gz \
          2>&1 | log_blob "${_LOG}" "fetch"; then
      temp_dir=$(mktemp -d /tmp/updates-XXXXX)
      tar -C "${temp_dir}" -xzf /tmp/updates.tar.gz
      for a in "${temp_dir}"/*.sh; do
        "${a}" "${phase}" 2>&1 | log_blob "${_LOG}" "update:$(basename $a)"
      done
      rm -rf "${temp_dir}" /tmp/updates.tar.gz
  else
    return 1
  fi
}


setup
require files
require log

_LOG=/var/log/clusterware/updater.log

main "$@"
