#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Flight Direct.
#
# Flight Direct is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Flight Direct is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Flight Direct, please visit:
# https://github.com/alces-software/flight-direct
#==============================================================================
_is_mounted() {
    cat /proc/mounts | grep -q " $1 nfs"
}

main() {
    local exports_json exports a tgt found
    if exports_json=$(handler_query nfs-exports); then
	exports=$(echo "${exports_json}" | jq -r .Responses[])
	for a in $exports; do
	    found=true
	    tgt=$(echo $a | cut -f2 -d":")
	    if _is_mounted $tgt; then
		echo "Already mounted: ${tgt}"
	    else
		echo "Mounting: $a on $tgt"
		mkdir -p "${tgt}"
		mount -t nfs "$a" "$tgt"
	    fi
	done
	if [ -z "$found" ]; then
	    action_die "no NFS exports are currently available"
	fi
    else
	action_die "unable to query cluster ring for available NFS exports"
    fi
}

require action
require handler

main "$@"
