#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Flight Direct.
#
# Flight Direct is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Flight Direct is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Flight Direct, please visit:
# https://github.com/alces-software/flight-direct
#==============================================================================
main() {
    local ev id script evdir
    ev="$1"
    id="$2"
    script="$3"
    evdir="${cw_ROOT}"/etc/events/"${id}"
    
    if [ "${ev}" -a "${id}" -a "${script}" ]; then
	if [ -f "$script" ]; then
	    echo "Setting listener for event '$ev': $id"
	    mkdir -p "${evdir}"
	    cp "$script" "${evdir}"/"${ev}"	    
	else
	    echo "${cw_BINNAME}: file not found: $script"
	    exit 1
	fi
    else
	echo "Usage: ${cw_BINNAME} <event> <id> <script>"
	exit 1
    fi
}

main "$@"
