#!/bin/bash
#==============================================================================
# Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Flight Direct.
#
# Flight Direct is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Flight Direct is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Flight Direct, please visit:
# https://github.com/alces-software/flight-direct
#==============================================================================
require handler

main() {
    if ! systemctl -q is-active flight-events; then
	echo "Flight Events service is not running."
    else
	if [ "$1" == "--local" ]; then
	    shift
	    echo "Locally triggering event: $1"
	    if ! handler_run_hook "$@"; then
		echo "Failed."
	    fi
	else
	    echo "Triggering event: $1"
	    if ! handler_broadcast "$@"; then
		echo "Failed."
	    fi
	fi
    fi
}

main "$@"
