#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.rc ]; then
            source "${a}"/clusterware/config.rc
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
  local hostname ip groupname group_max_size cores_per_node
  echo "Received autoscaling-member-join with args ${*}"

  if [[ "${cw_INSTANCE_tag_SCHEDULER_ROLES}" == *":master:"* ]]; then
    hostname="$1"
    ip="$2"
    groupname="$3"
    group_max_size="$4"
    cores_per_node="$5"

    handler_run_helper share/add-host-to-hostgroup "$hostname" "$groupname"
  fi
}

setup
require member
require network
require handler
require log
require files

files_load_config --optional cluster-sge
files_load_config instance config/cluster
log_set_default "${cw_CLUSTER_SGE_log:-/var/log/clusterware/cluster-sge.log}"
handler_tee main "$@"
