#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
if [ -d "${cw_ROOT}"/etc/config/domain-networking ]; then
    echo "Domain networking configuration has already been completed"
    exit 0
fi
curl -o /tmp/bumblebee.tar.gz https://s3-eu-west-1.amazonaws.com/packages.alces-software.com/clusterware/dist/private/el7/bumblebee.tar.gz
cd /opt
tar xvzf /tmp/bumblebee.tar.gz
cd bumblebee
. "${cw_ROOT}"/etc/ruby.rc
bundle install --local --path=vendor
export BUMBLEBEE_CONFIG="${cw_ROOT}"/etc/bumblebee.yml
while [ ! -f "${BUMBLEBEE_CONFIG}" ]; do
    sleep 1
    c=$(($c+1))
    if [ $c -gt 120 ]; then
        echo "No bumblebee configuration file was found after 120s."
        exit 1
    fi
done
if bin/bumblebee configure; then
    mkdir -p "${cw_ROOT}"/etc/config/domain-networking
    # Disable cloud-init's management of hostname
    sed -i -e 's/^preserve_hostname: false/preserve_hostname: true/g' /etc/cloud/cloud.cfg
    sed -i -e 's/#\?cw_CLUSTERABLE_manage_hostname=.*/cw_CLUSTERABLE_manage_hostname=false/g' \
        /opt/clusterware/etc/clusterable.rc
fi
