#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2018 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.rc ]; then
            source "${a}"/clusterware/config.rc
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
  if [ -d "${cw_ROOT}/etc/config/updater" ]; then
      "${cw_ROOT}"/libexec/share/apply-updates reboot
      return 0
  fi

  mkdir -p "${cw_ROOT}/etc/config/updater"

  if [ -d "${cw_ROOT}/etc/config/cluster" ]; then
      "${cw_ROOT}"/libexec/share/apply-updates postboot
  else
      "${cw_ROOT}"/libexec/share/apply-updates
  fi
}

setup
require handler

handler_tee main "$@"
